// useProgressNotes — list + create for the Finding/Task progress-note timeline (#377).
//
// The endpoint is the only difference between the two surfaces:
//   GET  /findings/:id/comments vs /tasks/:id/comments — cursor pagination
//        ({ createdAt, id } base64, newest-first pages, limit default 50).
//   POST /findings/:id/comments vs /tasks/:id/comments — Idempotency-Key is
//        auto-minted per call by apiRequest; `note` is the only kind FE ever
//        creates (status_change rows are server-generated by PATCH transitions).
//
// After a successful POST the list is re-fetched (not optimistically patched):
// the refetch also surfaces concurrent status_change rows the actor just caused.

import { createFindingComment, listFindingComments } from '@/lib/api/findings-comments';
import { createTaskComment, listTaskComments } from '@/lib/api/tasks-comments';
import type { ApiError } from '@/lib/api/types';
import type { FindingCommentDto, TaskCommentDto } from '@fops/shared';
import type { TipTapDoc } from '@fops/ui';
import { useInfiniteQuery, useMutation, useQueryClient } from '@tanstack/react-query';

import { extractMentions } from '../mentions/extractMentions';

export type ProgressNotesResource = { kind: 'finding'; id: string } | { kind: 'task'; id: string };

export type ProgressNoteDto = FindingCommentDto | TaskCommentDto;

/** Shape common to both surfaces' list responses (shared DTOs differ only in
 * `finding_id` vs `task_id`). Explicit so TanStack doesn't have to infer a
 * union from the endpoint ternary. */
export interface ProgressNotesPage {
  items: ProgressNoteDto[];
  page: { cursor?: string | undefined; has_more: boolean };
}

export function progressNotesQueryKey(resource: ProgressNotesResource) {
  return ['progress-notes', resource.kind, resource.id] as const;
}

export function useProgressNotesList(resource: ProgressNotesResource) {
  return useInfiniteQuery({
    queryKey: progressNotesQueryKey(resource),
    queryFn: async ({ pageParam, signal }): Promise<ProgressNotesPage> => {
      const cursor = (pageParam as string) || undefined;
      return resource.kind === 'finding'
        ? listFindingComments(resource.id, { ...(cursor !== undefined ? { cursor } : {}), signal })
        : listTaskComments(resource.id, { ...(cursor !== undefined ? { cursor } : {}), signal });
    },
    initialPageParam: '',
    getNextPageParam: (lastPage) =>
      lastPage.page.has_more && lastPage.page.cursor ? lastPage.page.cursor : undefined,
    enabled: Boolean(resource.id),
    staleTime: 10_000,
  });
}

export function useCreateProgressNote(
  resource: ProgressNotesResource,
  args: {
    onSuccess?: () => void;
    onError?: (error: ApiError) => void;
  } = {},
) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (doc: TipTapDoc): Promise<{ comment: ProgressNoteDto }> => {
      const body = { body_rich_content: doc, mentions: extractMentions(doc) };
      return resource.kind === 'finding'
        ? createFindingComment(resource.id, body)
        : createTaskComment(resource.id, body);
    },
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: progressNotesQueryKey(resource) });
      args.onSuccess?.();
    },
    onError: (error) => args.onError?.(error as ApiError),
  });
}
