import { z } from 'zod';

export const findingStatusSchema = z.enum([
  'draft',
  'active',
  'not_actionable',
  'converted',
  'archived',
]);
export type FindingStatus = z.infer<typeof findingStatusSchema>;

export const findingSeveritySchema = z.enum(['low', 'medium', 'high', 'critical']);
export type FindingSeverity = z.infer<typeof findingSeveritySchema>;

export const findingConfidenceSchema = z.enum(['low', 'medium', 'high']);
export type FindingConfidence = z.infer<typeof findingConfidenceSchema>;

export const evidenceHighlightSourceTypeSchema = z.enum(['voc', 'survey_response', 'note']);
export type EvidenceHighlightSourceType = z.infer<typeof evidenceHighlightSourceTypeSchema>;

export const evidenceHighlightSentimentSchema = z.enum(['negative', 'neutral', 'positive']);
export type EvidenceHighlightSentiment = z.infer<typeof evidenceHighlightSentimentSchema>;

export const evidenceHighlightImportanceSchema = z.enum(['low', 'medium', 'high']);
export type EvidenceHighlightImportance = z.infer<typeof evidenceHighlightImportanceSchema>;

export const createFindingRequestSchema = z
  .object({
    title: z.string().trim().min(1).max(200),
    summary: z.string().trim().min(1),
    severity: findingSeveritySchema,
    confidence: findingConfidenceSchema.optional(),
    analytics_area_id: z.string().uuid().optional(),
    primary_managed_system_id: z.string().uuid().optional(),
  })
  .strict();
export type CreateFindingRequest = z.infer<typeof createFindingRequestSchema>;

/**
 * Route-shaped request for POST /survey-responses/:id/create-finding.
 * Finding copy is generated by the backend so personal response text cannot
 * be laundered through caller-provided title or summary fields.
 */
export const createFindingFromSurveyResponseRequestSchema = z
  .object({
    severity: findingSeveritySchema,
    confidence: findingConfidenceSchema.optional(),
    analytics_area_id: z.string().uuid().optional(),
    primary_managed_system_id: z.string().uuid().optional(),
    approved_excerpt_ids: z.array(z.string().uuid()),
  })
  .strict();
export type CreateFindingFromSurveyResponseRequest = z.infer<
  typeof createFindingFromSurveyResponseRequestSchema
>;

/** Approved, redacted Survey text that is safe for Finding/Evidence reads. */
export const approvedExcerptDtoSchema = z
  .object({
    approved_excerpt_id: z.string().uuid(),
    question_id: z.string().uuid(),
    redacted_excerpt: z.string().min(1),
  })
  .strict();
export type ApprovedExcerptDto = z.infer<typeof approvedExcerptDtoSchema>;

/**
 * Raw personal-response text returned only by the audited candidate route.
 * It must never be embedded in a Finding, Evidence, result, or link DTO.
 */
export const surveyResponseExcerptCandidateDtoSchema = z
  .object({
    question_id: z.string().uuid(),
    question_label: z.string().min(1),
    raw_text: z.string(),
  })
  .strict();
export type SurveyResponseExcerptCandidateDto = z.infer<
  typeof surveyResponseExcerptCandidateDtoSchema
>;

export const listSurveyResponseExcerptCandidatesResponseSchema = z
  .object({
    items: z.array(surveyResponseExcerptCandidateDtoSchema),
  })
  .strict();
export type ListSurveyResponseExcerptCandidatesResponse = z.infer<
  typeof listSurveyResponseExcerptCandidatesResponseSchema
>;

export const patchFindingRequestSchema = z
  .object({
    status: findingStatusSchema,
    reason: z.string().trim().min(1).max(1000).optional(),
  })
  .strict();
export type PatchFindingRequest = z.infer<typeof patchFindingRequestSchema>;

export const linkTaskRequestSchema = z
  .object({
    task_id: z.string().uuid(),
  })
  .strict();
export type LinkTaskRequest = z.infer<typeof linkTaskRequestSchema>;

export const findingSourceSchema = z.discriminatedUnion('type', [
  z
    .object({
      type: z.enum(['voc', 'voc_cluster']),
      id: z.string().uuid(),
      relation_type: z.literal('created_finding'),
      link_id: z.string().uuid().optional(),
    })
    .strict(),
  z
    .object({
      type: z.literal('survey_response'),
      relation_type: z.literal('generated_finding'),
    })
    .strict(),
]);
export type FindingSource = z.infer<typeof findingSourceSchema>;

const findingDtoBaseSchema = {
  id: z.string().uuid(),
  workspace_id: z.string().uuid(),
  display_id: z.string(),
  primary_managed_system_id: z.string().uuid(),
  title: z.string(),
  summary: z.string(),
  evidence_count: z.number().int().nonnegative(),
  severity: findingSeveritySchema,
  confidence: findingConfidenceSchema.nullable(),
  status: findingStatusSchema,
  analytics_area_id: z.string().uuid().nullable(),
  linked_task_id: z.string().uuid().nullable(),
  linked_milestone_id: z.string().uuid().nullable(),
  created_by: z.string().uuid(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  source: findingSourceSchema.nullable().optional(),
};

export const findingDtoSchema = z.discriminatedUnion('source_type', [
  z
    .object({
      ...findingDtoBaseSchema,
      source_type: z.literal('voc'),
      source_id: z.string().uuid().nullable(),
    })
    .strict(),
  z
    .object({
      ...findingDtoBaseSchema,
      source_type: z.literal('voc_cluster'),
      source_id: z.string().uuid().nullable(),
    })
    .strict(),
  z
    .object({
      ...findingDtoBaseSchema,
      source_type: z.literal('survey'),
      source_id: z.string().uuid().nullable(),
    })
    .strict(),
  z
    .object({
      ...findingDtoBaseSchema,
      source_type: z.literal('survey_response'),
    })
    .strict(),
  z
    .object({
      ...findingDtoBaseSchema,
      source_type: z.literal('manual'),
      source_id: z.string().uuid().nullable(),
    })
    .strict(),
]);
export type FindingDto = z.infer<typeof findingDtoSchema>;

export const listFindingsResponseSchema = z
  .object({
    items: z.array(findingDtoSchema),
  })
  .strict();
export type ListFindingsResponse = z.infer<typeof listFindingsResponseSchema>;

export const addEvidenceHighlightRequestSchema = z
  .object({
    source_type: evidenceHighlightSourceTypeSchema,
    source_id: z.string().uuid().nullable().optional(),
    quote_or_summary: z.string().min(1),
    analytics_area_id: z.string().uuid().nullable().optional(),
    sentiment: evidenceHighlightSentimentSchema.nullable().optional(),
    importance: evidenceHighlightImportanceSchema.nullable().optional(),
  })
  .strict()
  .superRefine((value, ctx) => {
    if (value.source_type !== 'note' && value.source_id == null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['source_id'],
        message: 'source_id is required unless source_type is note',
      });
    }
  });
export type AddEvidenceHighlightRequest = z.infer<typeof addEvidenceHighlightRequestSchema>;

const evidenceHighlightDtoBaseSchema = {
  id: z.string().uuid(),
  workspace_id: z.string().uuid(),
  finding_id: z.string().uuid(),
  primary_managed_system_id: z.string().uuid(),
  quote_or_summary: z.string().optional(),
  analytics_area_id: z.string().uuid().nullable(),
  sentiment: evidenceHighlightSentimentSchema.nullable(),
  importance: evidenceHighlightImportanceSchema.nullable(),
  created_by: z.string().uuid(),
  created_at: z.string().datetime(),
};

export const evidenceHighlightDtoSchema = z.discriminatedUnion('source_type', [
  z
    .object({
      ...evidenceHighlightDtoBaseSchema,
      source_type: z.literal('voc'),
      // Keep the established nullable VOC source behavior while requiring the key.
      source_id: z.string().uuid().nullable(),
      source_title: z.string().nullable(),
      source_meta: z.string().nullable(),
    })
    .strict(),
  z
    .object({
      ...evidenceHighlightDtoBaseSchema,
      source_type: z.literal('survey_response'),
      source_title: z.literal('Survey response'),
      source_meta: z.string().regex(/^[^·]+ · [^·]+ · Identity protected$/),
    })
    .strict(),
  z
    .object({
      ...evidenceHighlightDtoBaseSchema,
      source_type: z.literal('note'),
      source_id: z.string().uuid().nullable(),
      source_title: z.string().nullable(),
      source_meta: z.string().nullable(),
    })
    .strict(),
]);
export type EvidenceHighlightDto = z.infer<typeof evidenceHighlightDtoSchema>;

export const listEvidenceHighlightsResponseSchema = z
  .object({
    items: z.array(evidenceHighlightDtoSchema),
  })
  .strict();
export type ListEvidenceHighlightsResponse = z.infer<typeof listEvidenceHighlightsResponseSchema>;

export const linkEvidenceRequestSchema = z
  .object({
    source_type: z.literal('voc'),
    source_id: z.string().uuid(),
  })
  .strict();
export type LinkEvidenceRequest = z.infer<typeof linkEvidenceRequestSchema>;
