import { z } from 'zod';

import { findingConfidenceSchema, findingSeveritySchema } from '../findings/index.js';

/**
 * Route-shaped request for POST /survey-responses/:id/create-finding.
 * Finding copy is generated by the backend so personal response text cannot
 * be laundered through caller-provided title or summary fields.
 */
export const createFindingFromSurveyResponseRequestSchema = z
  .object({
    severity: findingSeveritySchema,
    confidence: findingConfidenceSchema.optional(),
    analytics_area_id: z.string().uuid().optional(),
    primary_managed_system_id: z.string().uuid().optional(),
    approved_excerpt_ids: z.array(z.string().uuid()),
  })
  .strict();
export type CreateFindingFromSurveyResponseRequest = z.infer<
  typeof createFindingFromSurveyResponseRequestSchema
>;

/** Approved, redacted Survey text that is safe for Finding/Evidence reads. */
export const approvedExcerptDtoSchema = z
  .object({
    approved_excerpt_id: z.string().uuid(),
    question_id: z.string().uuid(),
    redacted_excerpt: z.string().min(1),
  })
  .strict();
export type ApprovedExcerptDto = z.infer<typeof approvedExcerptDtoSchema>;

/**
 * Raw personal-response text returned only by the audited candidate route.
 * It must never be embedded in a Finding, Evidence, result, or link DTO.
 */
export const surveyResponseExcerptCandidateDtoSchema = z
  .object({
    question_id: z.string().uuid(),
    question_label: z.string().min(1),
    raw_text: z.string(),
  })
  .strict();
export type SurveyResponseExcerptCandidateDto = z.infer<
  typeof surveyResponseExcerptCandidateDtoSchema
>;

export const listSurveyResponseExcerptCandidatesResponseSchema = z
  .object({
    items: z.array(surveyResponseExcerptCandidateDtoSchema),
  })
  .strict();
export type ListSurveyResponseExcerptCandidatesResponse = z.infer<
  typeof listSurveyResponseExcerptCandidatesResponseSchema
>;
