export const ADMIN_PERMISSIONS_COPY = {
  activeTitle: '활성 권한',
  listSubtitle: '부여된 권한과 차단을 확인하고 취소하거나 해제합니다.',
  grantsTab: '권한',
  deniesTab: '차단',
  tabLabel: '활성 권한 유형',
  loading: '활성 권한을 불러오는 중입니다.',
  error: '권한을 불러오지 못했습니다.',
  empty: '표시할 항목이 없습니다.',
  target: '대상자',
  permission: '권한',
  scope: '범위',
  grantor: '부여자',
  denier: '차단자',
  grantedAt: '부여일',
  deniedAt: '차단일',
  expiration: '만료',
  noExpiration: '만료 없음',
  denyReason: '차단 사유',
  id: 'ID',
  reasonLabel: '사유 · 필수',
  close: '닫기',
  closePanel: '패널 닫기',
  revokeGrant: '권한 취소',
  liftDeny: '차단 해제',
  reasonPlaceholder: '처리 사유를 입력하세요.',
  revokeSuccess: '권한을 취소했습니다.',
  liftSuccess: '차단을 해제했습니다.',
  permissionNotActive: '이미 처리되었거나 만료되어 더 이상 활성 상태가 아닙니다.',
  selfDenyLiftForbidden: '관리자는 본인에게 걸린 차단도 직접 해제할 수 없습니다.',
} as const;
