#!/usr/bin/env node
// AUTO-GENERATED target: scripts/wiki-regen.mjs
// Generates staged wiki markdown to docs/wiki-staging/.
// Run: pnpm wiki:regen
// Re-runnable and idempotent.

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from 'node:fs';
import { join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dir = fileURLToPath(new URL('.', import.meta.url));
const ROOT = join(__dir, '..');
const STAGING_DIR = join(ROOT, 'docs', 'wiki-staging');

mkdirSync(STAGING_DIR, { recursive: true });

const NOW = new Date().toISOString();
const HEADER = `<!-- AUTO-GENERATED by scripts/wiki-regen.mjs — do not hand-edit; run \`pnpm wiki:regen\` -->\n<!-- Generated: ${NOW} -->\n\n`;

// ─── helpers ────────────────────────────────────────────────────────────────

function readFileSafe(p) {
  try { return readFileSync(p, 'utf8'); } catch { return null; }
}

function writeStaging(name, content) {
  writeFileSync(join(STAGING_DIR, name), HEADER + content, 'utf8');
  console.log(`  wrote docs/wiki-staging/${name}`);
}

// ─── 1. api-catalog.md ──────────────────────────────────────────────────────

function buildApiCatalog() {
  const modulesDir = join(ROOT, 'apps', 'backend', 'src', 'modules');
  const modules = readdirSync(modulesDir, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);

  const rows = [];
  const scannedFiles = [];

  for (const mod of modules) {
    const routeFile = join(modulesDir, mod, 'routes.ts');
    if (!existsSync(routeFile)) continue;
    scannedFiles.push(routeFile.replace(ROOT + '/', ''));
    const src = readFileSafe(routeFile) ?? '';

    // Extract app.route({...}) blocks by scanning for the pattern
    // We find each `app.route({` and extract until matching close
    let pos = 0;
    while (pos < src.length) {
      const idx = src.indexOf('app.route({', pos);
      if (idx === -1) break;

      // Find the block by counting braces
      let depth = 0;
      let start = idx + 'app.route('.length;
      let blockStart = start;
      let blockEnd = -1;
      for (let i = start; i < src.length; i++) {
        if (src[i] === '{') depth++;
        else if (src[i] === '}') {
          depth--;
          if (depth === 0) { blockEnd = i; break; }
        }
      }
      if (blockEnd === -1) { pos = idx + 1; continue; }
      const block = src.slice(blockStart, blockEnd + 1);
      pos = blockEnd + 1;

      // method
      const methodM = block.match(/method:\s*['"]([A-Z]+)['"]/);
      if (!methodM) continue;
      const method = methodM[1];

      // url
      const urlM = block.match(/url:\s*['"]([^'"]+)['"]/);
      if (!urlM) continue;
      const url = urlM[1];

      // preHandler
      const preHandlerM = block.match(/preHandler:\s*\[([^\]]+)\]/);
      const preHandlerStr = preHandlerM ? preHandlerM[1] : '';
      const auth = [];
      if (/requireSession/.test(preHandlerStr)) auth.push('session');
      if (/requireWorkspace/.test(preHandlerStr)) auth.push('workspace');
      const authStr = auth.length ? auth.join('+') : '—';

      // rateLimit
      let rateLimit = '—';
      if (/rateLimit.*mutation/.test(block) || /rateLimitConfig\.mutation/.test(block)) {
        rateLimit = 'mutation';
      } else if (/rateLimit.*read/.test(block) || /rateLimitConfig\.read/.test(block)) {
        rateLimit = 'read';
      } else if (/rateLimit/.test(block)) {
        rateLimit = 'yes';
      }

      // Idempotency-Key: look in handler body for requireIdempotencyKey call
      const idempotency = /requireIdempotencyKey/.test(block) ? 'required' : '—';

      // If-Match: look for requireIfMatch call
      const ifMatch = /requireIfMatch/.test(block) ? 'required' : '—';

      rows.push({ method, url, module: mod, auth: authStr, rateLimit, idempotency, ifMatch });
    }
  }

  const header = `# API Catalog\n\nAll \`app.route()\` registrations found in \`apps/backend/src/modules/*/routes.ts\`.\n\n`;
  const tableHeader = `| Method | URL | Module | Auth | Rate-limit | Idempotency | If-Match |\n|---|---|---|---|---|---|---|\n`;
  const tableRows = rows
    .map(r => `| ${r.method} | \`${r.url}\` | ${r.module} | ${r.auth} | ${r.rateLimit} | ${r.idempotency} | ${r.ifMatch} |`)
    .join('\n');

  const footer = `\n\n## Source Files Scanned\n\n${scannedFiles.map(f => `- \`${f}\``).join('\n')}\n\n_Timestamp: ${NOW}_\n`;

  writeStaging('api-catalog.md', header + tableHeader + tableRows + footer);
}

// ─── 2. db-schema-map.md ────────────────────────────────────────────────────

/**
 * Extract a balanced brace block starting at `startIdx` in `src`.
 * Returns [blockContent, endIdx] where endIdx is the position AFTER the closing brace.
 */
function extractBraceBlock(src, startIdx) {
  let depth = 0;
  let start = -1;
  for (let i = startIdx; i < src.length; i++) {
    if (src[i] === '{') {
      if (start === -1) start = i;
      depth++;
    } else if (src[i] === '}') {
      depth--;
      if (depth === 0 && start !== -1) {
        return [src.slice(start + 1, i), i + 1];
      }
    }
  }
  return [null, startIdx];
}

function countTopLevelKeys(block) {
  // Count lines that look like `  identifier:` at depth 0
  let count = 0;
  let depth = 0;
  for (const line of block.split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('//') || t.startsWith('*')) continue;
    // track depth from chars before the key check
    const opens = (t.match(/\{|\[|\(/g) || []).length;
    const closes = (t.match(/\}|\]|\)/g) || []).length;
    if (depth === 0 && /^[a-zA-Z_$][\w$]*\s*:/.test(t)) count++;
    depth += opens - closes;
    if (depth < 0) depth = 0;
  }
  return count;
}

function buildDbSchemaMap() {
  const schemaDir = join(ROOT, 'apps', 'backend', 'src', 'db', 'schema');
  const files = readdirSync(schemaDir).filter(f => f.endsWith('.ts') && f !== 'index.ts');

  // Group by schema name
  const schemas = {};
  const scannedFiles = [];

  for (const f of files) {
    const filePath = join(schemaDir, f);
    scannedFiles.push(filePath.replace(ROOT + '/', ''));
    const src = readFileSafe(filePath) ?? '';

    // Extract pg schema name
    const schemaNameM = src.match(/pgSchema\(['"]([^'"]+)['"]\)/);
    const schemaName = schemaNameM ? schemaNameM[1] : basename(f, '.ts');

    if (!schemas[schemaName]) schemas[schemaName] = [];

    // Find all xxxSchema.table('name', {...}, (t) => ({...})) calls
    // We locate each `.table(` occurrence
    let pos = 0;
    while (pos < src.length) {
      const idx = src.indexOf('.table(', pos);
      if (idx === -1) break;

      const afterDot = src.slice(idx + 7); // after ".table("

      // Table name is the first string argument (may have whitespace before it)
      const nameM = afterDot.match(/^[\s\n\r]*['"`]([^'"`]+)['"`]/);
      if (!nameM) { pos = idx + 1; continue; }
      const tableName = nameM[1];

      // Skip to the comma after the name (first comma in afterDot)
      const commaIdx = afterDot.indexOf(',');
      if (commaIdx === -1) { pos = idx + 1; continue; }

      // Extract the column definition block (first brace block after the comma)
      const [colBlock, afterCols] = extractBraceBlock(src, idx + 7 + commaIdx);
      if (colBlock === null) { pos = idx + 1; continue; }

      const colCount = countTopLevelKeys(colBlock);

      // Look for the constraint callback: (t) => ({...}) immediately after the columns block
      // Find the next closing paren that ends the .table() call, then extract constraint block
      const remainingSrc = src.slice(afterCols);
      const constraintNames = [];
      // The constraint block is the NEXT brace block in remainingSrc (if it exists)
      // before the next .table( call
      const nextTableIdx = remainingSrc.indexOf('.table(');
      const constraintRegion = nextTableIdx > 0 ? remainingSrc.slice(0, nextTableIdx) : remainingSrc.slice(0, 3000);
      const constraintNameRe = /(?:check|uniqueIndex|primaryKey)\(\s*['"]([^'"]+)['"]/g;
      let cm;
      while ((cm = constraintNameRe.exec(constraintRegion)) !== null) {
        constraintNames.push(cm[1]);
      }

      // Only keep named CHECK constraints and unique indexes (exclude plain idx)
      const keyInvariants = constraintNames.filter(n =>
        n.endsWith('_check') || n.endsWith('_uq') || n.endsWith('_pk') ||
        n.includes('_xor') || n.includes('enum') || n.includes('_uq') ||
        n.includes('active_uq')
      );

      schemas[schemaName].push({
        table: tableName,
        columns: colCount,
        invariants: keyInvariants,
      });

      pos = afterCols;
    }
  }

  let content = `# DB Schema Map\n\nExtracted from \`apps/backend/src/db/schema/*.ts\`. Each entry shows table name, column count, and named CHECK/unique constraints (indexes omitted for brevity).\n\n`;

  for (const [schemaName, tables] of Object.entries(schemas)) {
    content += `## Schema: ${schemaName}\n\n`;
    content += `| Table | Columns | Key invariants |\n|---|---|---|\n`;
    for (const t of tables) {
      const inv = t.invariants.length ? t.invariants.join(', ') : '—';
      content += `| ${t.table} | ${t.columns} | ${inv} |\n`;
    }
    content += '\n';
  }

  content += `## Source Files Scanned\n\n${scannedFiles.map(f => `- \`${f}\``).join('\n')}\n\n_Timestamp: ${NOW}_\n`;

  writeStaging('db-schema-map.md', content);
}

// ─── 3. capability-matrix.md ─────────────────────────────────────────────────

function buildCapabilityMatrix() {
  const capsFile = join(ROOT, 'packages', 'shared', 'src', 'enums', 'capabilities.ts');
  const checkFile = join(ROOT, 'apps', 'backend', 'src', 'modules', 'permissions', 'check-service.ts');

  const capsSrc = readFileSafe(capsFile) ?? '';
  const checkSrc = readFileSafe(checkFile) ?? '';

  // Extract capabilities from CAPABILITIES array
  const capsM = capsSrc.match(/CAPABILITIES\s*=\s*\[([^\]]+)\]/);
  const caps = capsM
    ? [...capsM[1].matchAll(/['"]([^'"]+)['"]/g)].map(m => m[1])
    : [];

  // Extract sensitive flags from CAPABILITY_META
  const sensitiveMap = {};
  for (const cap of caps) {
    const re = new RegExp(`['"]${cap.replace('.', '\\.')}['"]\\s*:\\s*\\{[^}]*sensitive:\\s*(true|false)`);
    const m = capsSrc.match(re);
    sensitiveMap[cap] = m ? m[1] : '?';
  }

  // Parse roleSatisfies function to determine role grants
  // admin: all caps that appear in the admin branch
  // user: caps in user branch
  // developer: nothing implicit (needs MS scope)
  const adminCaps = new Set();
  const userCaps = new Set();

  const adminBlockM = checkSrc.match(/if\s*\(roleLevel\s*===\s*['"]admin['"]\)[^{]*\{([^}]+)\}/);
  if (adminBlockM) {
    const block = adminBlockM[1];
    const capRe = /capability\s*===\s*['"]([^'"]+)['"]/g;
    let m;
    while ((m = capRe.exec(block)) !== null) adminCaps.add(m[1]);
  }
  const userBlockM = checkSrc.match(/if\s*\(roleLevel\s*===\s*['"]user['"]\)[^{]*\{([^}]+)\}/);
  if (userBlockM) {
    const block = userBlockM[1];
    const capRe = /capability\s*===\s*['"]([^'"]+)['"]/g;
    let m;
    while ((m = capRe.exec(block)) !== null) userCaps.add(m[1]);
  }

  let content = `# Capability Matrix\n\nDerived from \`packages/shared/src/enums/capabilities.ts\` (capability list + sensitive flag) and \`apps/backend/src/modules/permissions/check-service.ts\` (\`roleSatisfies\` function).\n\n`;
  content += `| Capability | Sensitive | Admin (role) | Developer (role) | User (role) |\n`;
  content += `|---|---|---|---|---|\n`;

  for (const cap of caps) {
    const sensitive = sensitiveMap[cap] === 'true' ? 'yes' : 'no';
    const admin = adminCaps.has(cap) ? '✓ (implicit)' : '—';
    const developer = '— (MS-scoped grant required)';
    const user = userCaps.has(cap) ? '✓ (implicit)' : '—';
    content += `| ${cap} | ${sensitive} | ${admin} | ${developer} | ${user} |\n`;
  }

  content += `\n## Notes\n\n- Admin role satisfies all capabilities workspace-wide via \`roleSatisfies\`.\n- Developer role has no implicit capabilities; requires MS-scoped permission grant per ADR-0019.\n- User role satisfies \`workspace.read\` only.\n- Explicit deny (permission.permission_denies) overrides any grant or role rule.\n\n`;
  content += `## Sources\n\n- \`packages/shared/src/enums/capabilities.ts\`\n- \`apps/backend/src/modules/permissions/check-service.ts\`\n\n_Timestamp: ${NOW}_\n`;

  writeStaging('capability-matrix.md', content);
}

// ─── main ───────────────────────────────────────────────────────────────────

console.log('wiki-regen: generating docs/wiki-staging/ ...');
buildApiCatalog();
buildDbSchemaMap();
buildCapabilityMatrix();
console.log('wiki-regen: done.');
