import { Button, Input, Select, SelectContent, SelectItem, SelectTrigger, SelectValue, Textarea } from '@fops/ui';
import { Eye, Plus, Trash2 } from 'lucide-react';
import * as React from 'react';
import { useSurveyQuestionMutations } from '../../hooks/useSurveys';
import type { QuestionInput, QuestionKind, Survey, SurveyQuestion } from '../../types';

const kinds: Array<{ value: QuestionKind; label: string }> = [
  { value: 'single_choice', label: 'Single choice' }, { value: 'multiple_choice', label: 'Multiple choice' }, { value: 'rating', label: 'Rating' }, { value: 'text', label: 'Text' },
];
function newQuestion(surveyId: string, order: number): SurveyQuestion { return { id: `local-${crypto.randomUUID()}`, survey_id: surveyId, kind: 'single_choice', prompt: '새 질문', is_required: false, options: [{ key: 'option-1', label: 'Option 1' }, { key: 'option-2', label: 'Option 2' }], rating_min: null, rating_max: null, rating_low_label: null, rating_high_label: null, sort_order: order, branch_depth: 0, branch_parent_question_id: null, branch_trigger_option_key: null }; }
function toInput(question: SurveyQuestion): QuestionInput { const { id: _id, survey_id: _survey, branch_depth: _depth, ...input } = question; return input; }

export function SurveyBuilder({ survey, canManage, gateState, onBack }: { survey: Survey; canManage: boolean; gateState?: 'loading' | 'error' | 'absent'; onBack: () => void }) {
  const [questions, setQuestions] = React.useState<SurveyQuestion[]>(survey.questions ?? []);
  const [selectedId, setSelectedId] = React.useState<string | null>(questions[0]?.id ?? null);
  const [preview, setPreview] = React.useState(false);
  const mutations = useSurveyQuestionMutations(survey.id);
  const editable = canManage && survey.status === 'draft' && !gateState;
  const selected = questions.find((question) => question.id === selectedId) ?? null;
  const patch = (next: SurveyQuestion) => { setQuestions((all) => all.map((question) => question.id === next.id ? next : question)); if (!next.id.startsWith('local-')) mutations.update.mutate({ id: next.id, body: toInput(next) }); };
  const add = () => { const question = newQuestion(survey.id, questions.length); setQuestions((all) => [...all, question]); setSelectedId(question.id); void mutations.create.mutateAsync(toInput(question)).then((created) => setQuestions((all) => all.map((item) => item.id === question.id ? { ...question, id: created.id } : item))); };
  const remove = (id: string) => { setQuestions((all) => all.filter((question) => question.id !== id)); if (!id.startsWith('local-')) mutations.remove.mutate(id); };
  return <main className="flex h-full flex-col bg-surface-canvas" data-testid="survey-builder"><header className="flex h-toolbar items-center gap-3 border-b border-border-subtle px-4"><Button variant="ghost" size="sm" onClick={onBack}>Back</Button><div className="min-w-0 flex-1"><h1 className="truncate font-semibold">{survey.title}</h1><span className="text-xs text-text-muted">Draft · {survey.type}</span></div><Button variant="subtle" size="sm" onClick={() => setPreview(true)}><Eye className="h-4 w-4" />Preview</Button></header>{!editable && <div className="border-b border-border-subtle bg-surface-detail px-4 py-3 text-sm text-text-muted">{survey.status !== 'draft' ? 'Live 상태 — 질문 변경은 잠겨 있습니다.' : '설문 관리 권한이 없습니다.'}</div>}<div className="grid min-h-0 flex-1 grid-cols-[280px_minmax(0,1fr)_300px]"><section className="border-r border-border-subtle p-3"><div className="mb-3 flex items-center justify-between"><span className="text-sm font-medium">Questions {questions.length}</span>{editable && <Button size="sm" onClick={add}><Plus className="h-4 w-4" />새 질문 추가</Button>}</div><div className="space-y-1">{questions.map((question, index) => <button key={question.id} type="button" onClick={() => setSelectedId(question.id)} className="flex w-full items-center gap-2 rounded px-2 py-2 text-left text-sm hover:bg-surface-card"><span>Q{index + 1}</span><span className="min-w-0 flex-1 truncate">{question.prompt || '제목 없음'}</span>{editable && <span onClick={(event) => { event.stopPropagation(); remove(question.id); }} aria-label="질문 삭제"><Trash2 className="h-3.5 w-3.5" /></span>}</button>)}</div></section><section className="min-w-0 overflow-auto p-5">{selected ? <QuestionEditor question={selected} questions={questions} editable={editable} onChange={patch} /> : <p className="text-sm text-text-muted">질문을 선택하거나 새로 추가하세요.</p>}</section><aside className="border-l border-border-subtle p-4"><p className="text-xs uppercase text-text-muted">Survey settings</p><p className="mt-3 text-sm">Managed System</p><p className="text-xs text-text-muted break-all">{survey.primary_managed_system_id}</p><p className="mt-5 text-sm">응답 익명성</p><p className="text-xs text-text-muted">{survey.responses_identity_protected ? '익명 응답' : '식별 가능 응답'}</p><p className="mt-5 text-xs text-text-muted">Survey Response → VOC 생성은 금지됩니다.</p></aside></div>{preview && <PreviewPane survey={{ ...survey, questions }} onClose={() => setPreview(false)} />}</main>;
}

function QuestionEditor({ question, questions, editable, onChange }: { question: SurveyQuestion; questions: SurveyQuestion[]; editable: boolean; onChange: (question: SurveyQuestion) => void }) { const set = (patch: Partial<SurveyQuestion>) => onChange({ ...question, ...patch }); const parent = questions.find((candidate) => candidate.id === question.branch_parent_question_id); return <div className="space-y-4"><label className="block text-sm">Question kind<Select value={question.kind} disabled={!editable} onValueChange={(kind) => set({ kind: kind as QuestionKind, options: kind === 'single_choice' || kind === 'multiple_choice' ? question.options ?? [{ key: 'option-1', label: 'Option 1' }, { key: 'option-2', label: 'Option 2' }] : null, rating_min: kind === 'rating' ? 1 : null, rating_max: kind === 'rating' ? 5 : null })}><SelectTrigger aria-label="Question kind"><SelectValue /></SelectTrigger><SelectContent>{kinds.map((kind) => <SelectItem key={kind.value} value={kind.value}>{kind.value}</SelectItem>)}</SelectContent></Select></label><label className="block text-sm">Question title<Textarea value={question.prompt} disabled={!editable} onChange={(event) => set({ prompt: event.target.value })} /></label>{(question.kind === 'single_choice' || question.kind === 'multiple_choice') && <OptionsEditor question={question} editable={editable} onChange={set} />}{question.kind === 'rating' && <div className="grid grid-cols-2 gap-2"><Input aria-label="최소 점수" type="number" value={question.rating_min ?? 1} disabled={!editable} onChange={(event) => set({ rating_min: Number(event.target.value) })} /><Input aria-label="최대 점수" type="number" value={question.rating_max ?? 5} disabled={!editable} onChange={(event) => set({ rating_max: Number(event.target.value) })} /></div>}<label className="flex gap-2 text-sm"><input type="checkbox" checked={question.is_required} disabled={!editable} onChange={(event) => set({ is_required: event.target.checked })} />필수 질문</label>{editable && <label className="block text-sm">조건부로 다음 질문을 보여주기 (one-level)<select className="mt-1 w-full rounded border border-border-subtle bg-surface-canvas p-2" value={question.branch_parent_question_id ?? ''} onChange={(event) => { const parentId = event.target.value || null; const nextParent = questions.find((candidate) => candidate.id === parentId); set({ branch_parent_question_id: parentId, branch_trigger_option_key: parentId ? nextParent?.options?.[0]?.key ?? null : null }); }}><option value="">분기 없음</option>{questions.filter((candidate) => candidate.id !== question.id && candidate.kind === 'single_choice' && !candidate.branch_parent_question_id).map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.prompt || candidate.id}</option>)}</select>{parent && <p className="mt-1 text-xs text-text-muted">{parent.prompt}의 첫 옵션을 선택한 경우에만 표시됩니다.</p>}</label>}</div>; }
function OptionsEditor({ question, editable, onChange }: { question: SurveyQuestion; editable: boolean; onChange: (patch: Partial<SurveyQuestion>) => void }) { return <div className="space-y-2"><p className="text-sm">Options</p>{(question.options ?? []).map((option, index) => <Input key={option.key} value={option.label} disabled={!editable} onChange={(event) => onChange({ options: (question.options ?? []).map((item, current) => current === index ? { ...item, label: event.target.value } : item) })} />)}</div>; }
function PreviewPane({ survey, onClose }: { survey: Survey; onClose: () => void }) { return <div className="fixed inset-0 z-50 grid grid-cols-[1fr_480px] bg-black/20" role="dialog" aria-label="Respondent preview"><button type="button" aria-label="미리보기 닫기" onClick={onClose} /><section className="overflow-auto bg-surface-canvas p-6"><div className="flex justify-between"><p className="text-sm font-medium">Respondent preview</p><Button size="sm" variant="ghost" onClick={onClose}>닫기</Button></div><h2 className="mt-6 text-xl font-semibold">{survey.title || '제목 없음'}</h2><p className="mt-1 text-sm text-text-muted">{survey.description || '아직 설명이 추가되지 않았습니다.'}</p><div className="mt-6 space-y-6">{(survey.questions ?? []).filter((question) => !question.branch_parent_question_id).map((question, index) => <div key={question.id}><p className="text-sm font-medium">Q{index + 1}. {question.prompt || '제목 없음'}{question.is_required && ' *'}</p><PreviewInput question={question} /></div>)}</div><p className="mt-8 text-xs text-text-muted">{survey.questions?.length ?? 0}개 질문 · 실제 응답은 저장되지 않습니다.</p></section></div>; }
function PreviewInput({ question }: { question: SurveyQuestion }) { if (question.kind === 'text') return <Textarea placeholder="자유롭게 적어주세요…" />; if (question.kind === 'rating') return <div className="mt-2 flex gap-2">{Array.from({ length: (question.rating_max ?? 5) - (question.rating_min ?? 1) + 1 }, (_, index) => <button key={index} className="h-8 w-8 rounded-full border border-border-subtle">{(question.rating_min ?? 1) + index}</button>)}</div>; return <div className="mt-2 space-y-2">{(question.options ?? []).map((option) => <label key={option.key} className="flex gap-2 text-sm"><input type={question.kind === 'single_choice' ? 'radio' : 'checkbox'} name={question.id} />{option.label}</label>)}</div>; }
