-- Slice 2 #9 (ADR-0017 + ADR-0018): managed_systems + analytics_areas + teams.
--
-- ADR-0017 locks the Managed System Registry shape:
--   * UUID PK + workspace-scoped immutable `slug` + mutable `name` +
--     optional `external_key` (metadata only, not a sync key).
--   * Archive over hard delete: `archived_at` + `archived_by_actor_id`,
--     slug reusable after archive via partial unique
--     (`WHERE archived_at IS NULL`).
--   * Analytics Area is flat under exactly one Managed System (no
--     `parent_analytics_area_id`). Two MSs may carry the same AA slug.
--
-- ADR-0018 binds `core.teams` to this slice as a placeholder — schema +
-- FK target only. No CRUD, no admin UI, no seed rows. The default-owner
-- XOR-or-both-null CHECK on `managed_systems` enforces "Actor *or* team"
-- per CONTEXT.md:103 so downstream consumers (Slice 3 default-owner
-- resolution) have a single answer per row.
--
-- Drizzle-kit's CJS loader cannot resolve the `.js` extension that
-- NodeNext requires for cross-file `.ts` imports (same issue documented
-- in migration 0003). To keep the migration self-contained and
-- reviewable, all DDL is hand-written here rather than partially
-- autogenerated. The Drizzle schema in `src/db/schema/core.ts` mirrors
-- the shape 1:1 for typed access.

-- ─── core.teams (ADR-0018 placeholder) ─────────────────────────────────
CREATE TABLE "core"."teams" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "workspace_id" uuid NOT NULL,
  "name" text NOT NULL,
  "archived_at" timestamp with time zone,
  "archived_by_actor_id" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "core"."teams"
  ADD CONSTRAINT "teams_workspace_id_workspaces_id_fk"
  FOREIGN KEY ("workspace_id") REFERENCES "core"."workspaces"("id")
  ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "core"."teams"
  ADD CONSTRAINT "teams_archived_by_actor_id_actors_id_fk"
  FOREIGN KEY ("archived_by_actor_id") REFERENCES "core"."actors"("id")
  ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "teams_workspace_idx" ON "core"."teams" USING btree ("workspace_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "teams_workspace_name_active_uq"
  ON "core"."teams"
  USING btree ("workspace_id","name")
  WHERE "archived_at" is null;
--> statement-breakpoint

-- ─── core.managed_systems (ADR-0017) ───────────────────────────────────
CREATE TABLE "core"."managed_systems" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "workspace_id" uuid NOT NULL,
  "slug" text NOT NULL,
  "name" text NOT NULL,
  "external_key" text,
  "default_owner_actor_id" uuid,
  "default_owner_team_id" uuid,
  "archived_at" timestamp with time zone,
  "archived_by_actor_id" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "managed_systems_default_owner_xor_check"
    CHECK ("default_owner_actor_id" is null or "default_owner_team_id" is null)
);
--> statement-breakpoint
ALTER TABLE "core"."managed_systems"
  ADD CONSTRAINT "managed_systems_workspace_id_workspaces_id_fk"
  FOREIGN KEY ("workspace_id") REFERENCES "core"."workspaces"("id")
  ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "core"."managed_systems"
  ADD CONSTRAINT "managed_systems_default_owner_actor_id_actors_id_fk"
  FOREIGN KEY ("default_owner_actor_id") REFERENCES "core"."actors"("id")
  ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "core"."managed_systems"
  ADD CONSTRAINT "managed_systems_default_owner_team_id_teams_id_fk"
  FOREIGN KEY ("default_owner_team_id") REFERENCES "core"."teams"("id")
  ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "core"."managed_systems"
  ADD CONSTRAINT "managed_systems_archived_by_actor_id_actors_id_fk"
  FOREIGN KEY ("archived_by_actor_id") REFERENCES "core"."actors"("id")
  ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "managed_systems_workspace_idx" ON "core"."managed_systems" USING btree ("workspace_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "managed_systems_workspace_slug_active_uq"
  ON "core"."managed_systems"
  USING btree ("workspace_id","slug")
  WHERE "archived_at" is null;
--> statement-breakpoint

-- ─── core.analytics_areas (ADR-0017) ───────────────────────────────────
CREATE TABLE "core"."analytics_areas" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "workspace_id" uuid NOT NULL,
  "managed_system_id" uuid NOT NULL,
  "slug" text NOT NULL,
  "name" text NOT NULL,
  "owner_team_id" uuid,
  "archived_at" timestamp with time zone,
  "archived_by_actor_id" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "core"."analytics_areas"
  ADD CONSTRAINT "analytics_areas_workspace_id_workspaces_id_fk"
  FOREIGN KEY ("workspace_id") REFERENCES "core"."workspaces"("id")
  ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "core"."analytics_areas"
  ADD CONSTRAINT "analytics_areas_managed_system_id_managed_systems_id_fk"
  FOREIGN KEY ("managed_system_id") REFERENCES "core"."managed_systems"("id")
  ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "core"."analytics_areas"
  ADD CONSTRAINT "analytics_areas_owner_team_id_teams_id_fk"
  FOREIGN KEY ("owner_team_id") REFERENCES "core"."teams"("id")
  ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "core"."analytics_areas"
  ADD CONSTRAINT "analytics_areas_archived_by_actor_id_actors_id_fk"
  FOREIGN KEY ("archived_by_actor_id") REFERENCES "core"."actors"("id")
  ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "analytics_areas_workspace_idx" ON "core"."analytics_areas" USING btree ("workspace_id");
--> statement-breakpoint
CREATE INDEX "analytics_areas_workspace_managed_system_idx"
  ON "core"."analytics_areas" USING btree ("workspace_id","managed_system_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "analytics_areas_workspace_ms_slug_active_uq"
  ON "core"."analytics_areas"
  USING btree ("workspace_id","managed_system_id","slug")
  WHERE "archived_at" is null;
--> statement-breakpoint

-- ─── Role grants per ADR-0008 ──────────────────────────────────────────
-- fops_migrate owns DDL/DML; fops_app gets full DML on all three tables
-- (teams is grant-symmetric per ADR-0018 even though no Slice 2 service
-- writes to it — keeps the role-grant pattern uniform for the placeholder).
GRANT ALL ON "core"."managed_systems" TO fops_migrate;--> statement-breakpoint
GRANT ALL ON "core"."analytics_areas" TO fops_migrate;--> statement-breakpoint
GRANT ALL ON "core"."teams" TO fops_migrate;--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON "core"."managed_systems" TO fops_app;--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON "core"."analytics_areas" TO fops_app;--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON "core"."teams" TO fops_app;
